apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tiller-role
  namespace: kube-system
rules:
- apiGroups: ["", "extensions", "apps", "batch"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tiller-rolebinding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: tiller
roleRef:
  kind: Role
  name: tiller-role
  apiGroup: rbac.authorization.k8s.io